#!/usr/bin/env bash
# Bash script that configures an Ubuntu server:
# localhost -> 127.0.0.2
# facebook.com -> 8.8.8.8

# köhnə localhost və facebook.com sətirlərini sil
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts

# yeni hostları əlavə et
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
